version: '3.8'

services:
  db:
    image: postgres:12.22
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservas-app
    restart: always
    ports:
      - "${PORT}:4000"
    environment:
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SECRETKEY: ${SECRETKEY}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      - db
    networks:
      - app-network
    command: ["sh", "-c", "cd /app && npm run migrate:latest && npm run migrate:reset && npm run start"]


networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
