openapi: 3.0.0
info:
  title: Reservation Api
  summary: Summary.
  description: Description.
  version: 0.2.0
servers:
  - url: http://localhost:4000/api
    description: Staging server

security:
    - ApiKeyAuth: [ ]
tags:
  - name: Users
    description: Module in which you can manage everything related to Users
  - name: Rooms
    description: Module in which you can manage everything related to Rooms
  - name: Reservations
    description: Module in which you can manage everything related to Rooms

paths:
  /users:
    $ref: "./users/users.yaml#/users"
  /users/{id}:
    $ref: "./users/users.yaml#/users_id"
  /users/{id}/delete:
    $ref: "./users/users.yaml#/users_delete"
  /users/search:
    $ref: "./users/users.yaml#/users_search"

  /rooms:
    $ref: "./rooms/rooms.yaml#/rooms"
  /rooms/{id}:
    $ref: "./rooms/rooms.yaml#/rooms_id"
  /rooms/{id}/delete:
    $ref: "./rooms/rooms.yaml#/rooms_delete"
  /rooms/search:
    $ref: "./rooms/rooms.yaml#/rooms_search"


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-token


